### ISSUE TITLE
Dependents

### ISSUE THREAD

**Issue by szepeviktor** [norskeld/sigma#91]
### What problem does this feature solve?

`sigma` is so well written, feature packed, and to a high level of perfection.
How come that no one uses it?
https://www.npmjs.com/package/@nrsk/sigma

**Comment by norskeld** [comment]
Thanks for the kind words! I think it's far from perfection, but hopefully will become better over time. :)

> How come that no one uses it?

Well, some libs or apps may be private, so they obviously won't show up in "dependents" list, but mainly because no one knows about it, I guess. I don't promote my pet projects, so c’est la vie.

Also probably because there exist way more powerful libraries for parsing. Mostly parser generator frameworks or something like that, and mostly with subpar TypeScript support.
